"""empty message

Revision ID: 31e8c88250d0
Revises: 17c296008fe2
Create Date: 2019-10-03 16:16:01.511992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e8c88250d0'
down_revision = '17c296008fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('subscriber_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['subscriber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'subscriber_id')
    # ### end Alembic commands ###
